### ISSUE TITLE
More background

### ISSUE THREAD

**Issue by spaceOoooo** [emedd33/Reinforcement-Learning-in-Process-Control#3]
Hi,
Could you pls tell more about the background for this project? thanks

**Comment by emedd33** [comment]
Wow. 
How have I gone over 2 years and not seen this comment... haha. 
Dont know if its still of interest but the project was to see if the new RL method from machine learning could be of use as control model for industrial systems. Replacing traditional controllers like P-controller and MPC. So this is more of a POC to see if its viable to throw a RL algorithm on a industrial system which needs to be controlled. 

The motivation is that some large complex industrial systems have have modelsequations which need to be solved in order to have a control-model. And the solution is based on the system equations. So this project was to figure out if one could give the system to the Machine, without any knowledge about the system and see if it could learn to control the state. 

Also added the abstraction to the README file
